version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=viqnddcf
      - POSTGRES_USER=viqnddcf
      - POSTGRES_PASSWORD=AbCyiNwQq0gASW6KV4CvIdrKCvebtZLD
